Repository LikeLion12-Team1/Team1-Back, pull requests merged in 2024-07, with the labels that each got.

#1 :sparkles: [FEATURE] 인증 인가, QueryDsl 환경, 이메일 환경 추가
  build.gradle
  src/main/java/com/magnetic/MagneticApplication.java
  src/main/java/com/magnetic/config/ApplicationConfig.java
  src/main/java/com/magnetic/config/EmailConfig.java
  src/main/java/com/magnetic/config/QueryDslConfig.java
  src/main/java/com/magnetic/config/SecurityConfig.java
  src/main/java/com/magnetic/config/SwaggerConfig.java
  src/main/java/com/magnetic/domain/auth/controller/AuthController.java
  src/main/java/com/magnetic/domain/auth/dto/AuthRequestDto.java
  src/main/java/com/magnetic/domain/auth/dto/AuthResponseDto.java
  src/main/java/com/magnetic/domain/auth/dto/RegisterRequestDto.java
  src/main/java/com/magnetic/domain/auth/entity/Token.java
  src/main/java/com/magnetic/domain/auth/entity/TokenBlackList.java
  src/main/java/com/magnetic/domain/auth/entity/enums/TokenType.java
  src/main/java/com/magnetic/domain/auth/repository/TokenBlackListRepository.java
  src/main/java/com/magnetic/domain/auth/repository/TokenRepository.java
  src/main/java/com/magnetic/domain/auth/service/AuthService.java
  src/main/java/com/magnetic/domain/auth/service/LogoutService.java
  src/main/java/com/magnetic/domain/email/controller/EmailController.java
  src/main/java/com/magnetic/domain/email/dto/EmailRequestDto.java
  src/main/java/com/magnetic/domain/email/service/EmailService.java
  src/main/java/com/magnetic/domain/user/entity/User.java
  src/main/java/com/magnetic/domain/user/entity/enums/Role.java
  src/main/java/com/magnetic/domain/user/repository/UserRepository.java
  src/main/java/com/magnetic/global/common/exception/handler/AuthHandler.java
  src/main/java/com/magnetic/security/ApplicationAuditAware.java
  src/main/java/com/magnetic/security/CustomLogoutSuccessHandler.java
  src/main/java/com/magnetic/security/JwtService.java
  src/main/java/com/magnetic/security/filter/JwtAuthenticationFilter.java
Labels: :sparkles: feature

#4 :sparkles: [FEATURE] 메일 인증, 비밀번호 재설정 기능 추가
  src/main/java/com/magnetic/domain/email/controller/EmailController.java
  src/main/java/com/magnetic/domain/email/dto/EmailRequestDto.java
  src/main/java/com/magnetic/domain/email/service/EmailService.java
  src/main/java/com/magnetic/domain/user/controller/UserController.java
  src/main/java/com/magnetic/domain/user/dto/UserRequestDto.java
  src/main/java/com/magnetic/domain/user/service/UserService.java
Labels: :sparkles: feature

#10 ✨ [FEATURE] S3 환경 설정, Dockerfile 추가
  Dockerfile
  build.gradle
  src/main/java/com/magnetic/config/S3Config.java
  src/main/java/com/magnetic/config/SecurityConfig.java
  src/main/java/com/magnetic/domain/auth/service/AuthService.java
  src/main/java/com/magnetic/domain/email/controller/EmailController.java
  src/main/java/com/magnetic/domain/email/dto/EmailRequestDto.java
  src/main/java/com/magnetic/domain/email/dto/EmailResponseDto.java
  src/main/java/com/magnetic/domain/user/service/UserService.java
  src/main/java/com/magnetic/s3/S3Manager.java
  src/main/java/com/magnetic/s3/entity/Uuid.java
  src/main/java/com/magnetic/s3/repository/UuidRepository.java
Labels: :sparkles: feature

#12 :sparkles: feat: UserProfile 작업 내용 저장
  src/main/java/com/magnetic/domain/crew/entity/Crew.java
  src/main/java/com/magnetic/domain/crew/repository/CrewRepository.java
  src/main/java/com/magnetic/domain/user/controller/UserController.java
  src/main/java/com/magnetic/domain/user/converter/UserConverter.java
  src/main/java/com/magnetic/domain/user/dto/UserRequestDto.java
  src/main/java/com/magnetic/domain/user/dto/UserResponseDto.java
  src/main/java/com/magnetic/domain/user/entity/User.java
  src/main/java/com/magnetic/domain/user/entity/UserCrew.java
  src/main/java/com/magnetic/domain/user/repository/UserCrewRepository.java
  src/main/java/com/magnetic/domain/user/service/UserService.java
Labels: :sparkles: feature

#14 ✨ [FEATURE] merge Yejin into main
  src/main/java/com/magnetic/domain/alarm/entity/Alarm.java
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/controller/LikeController.java
  src/main/java/com/magnetic/domain/crew/controller/PostController.java
  src/main/java/com/magnetic/domain/crew/dto/request/crewdto/CreateCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/crewdto/JoinCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/crewdto/LeaveCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/crewdto/UpdateCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/likedto/LikeRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/postdto/CreatePostRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/postdto/UpdatePostRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/replydto/CreateReplyRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/replydto/UpdateReplyRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/response/CrewResponseDto.java
  src/main/java/com/magnetic/domain/crew/dto/response/PostResponseDto.java
  src/main/java/com/magnetic/domain/crew/entity/Crew.java
  src/main/java/com/magnetic/domain/crew/entity/CrewPost.java
  src/main/java/com/magnetic/domain/crew/entity/Like.java
  src/main/java/com/magnetic/domain/crew/entity/Post.java
  src/main/java/com/magnetic/domain/crew/entity/Reply.java
  src/main/java/com/magnetic/domain/crew/repository/CrewPostRepository.java
  src/main/java/com/magnetic/domain/crew/repository/LikeRepository.java
  src/main/java/com/magnetic/domain/crew/repository/PostRepository.java
  src/main/java/com/magnetic/domain/crew/repository/ReplyRepository.java
  src/main/java/com/magnetic/domain/crew/service/CrewService.java
  src/main/java/com/magnetic/domain/crew/service/LikeService.java
  src/main/java/com/magnetic/domain/crew/service/PostService.java
  src/main/java/com/magnetic/domain/user/controller/UserController.java
  src/main/java/com/magnetic/domain/user/entity/User.java
  src/main/java/com/magnetic/domain/user/service/UserService.java
Labels: :sparkles: feature

#15 ✨ [FEATURE] 프로필 수정, 소속 크루 탈퇴 기능 추가 및 사소한 수정
  src/main/java/com/magnetic/domain/user/controller/UserController.java
  src/main/java/com/magnetic/domain/user/entity/User.java
  src/main/java/com/magnetic/domain/user/service/UserService.java
Labels: :sparkles: feature

#16 ✨ [FEATURE] Challenge 목록 조회 기능, Crew 이름 중복 검사 기능 추가
  src/main/java/com/magnetic/domain/challenge/controller/ChallengeController.java
  src/main/java/com/magnetic/domain/challenge/converter/ChallengeConverter.java
  src/main/java/com/magnetic/domain/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/magnetic/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/magnetic/domain/challenge/entity/Challenge.java
  src/main/java/com/magnetic/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/magnetic/domain/challenge/repository/ChallengeRepositoryCustom.java
  src/main/java/com/magnetic/domain/challenge/repository/impl/ChallengeRepositoryImpl.java
  src/main/java/com/magnetic/domain/challenge/service/ChallengeService.java
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/entity/Crew.java
  src/main/java/com/magnetic/domain/crew/entity/CrewChallenge.java
  src/main/java/com/magnetic/domain/crew/entity/CrewPost.java
  src/main/java/com/magnetic/domain/crew/entity/Post.java
  src/main/java/com/magnetic/domain/crew/repository/CrewRepository.java
  src/main/java/com/magnetic/domain/crew/service/CrewService.java
  src/main/java/com/magnetic/domain/user/controller/MyPageController.java
  src/main/java/com/magnetic/domain/user/controller/UserController.java
  src/main/java/com/magnetic/domain/user/entity/User.java
  src/main/java/com/magnetic/domain/user/entity/UserChallenge.java
  src/main/java/com/magnetic/security/filter/JwtAuthenticationFilter.java
Labels: :sparkles: feature

#17 :sparkles: feat: MyPage 레이어 추가
  src/main/java/com/magnetic/domain/user/controller/MyPageController.java
  src/main/java/com/magnetic/domain/user/converter/MyPageConverter.java
  src/main/java/com/magnetic/domain/user/dto/MyPageResponseDto.java
  src/main/java/com/magnetic/domain/user/service/MyPageService.java
Labels: :sparkles: feature

#18 ✨ [FEATURE] 마이페이지 조회 기능 추가
  src/main/java/com/magnetic/domain/challenge/entity/Challenge.java
  src/main/java/com/magnetic/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/magnetic/domain/crew/entity/Crew.java
  src/main/java/com/magnetic/domain/user/controller/UserController.java
  src/main/java/com/magnetic/domain/user/converter/MyPageConverter.java
  src/main/java/com/magnetic/domain/user/converter/UserConverter.java
  src/main/java/com/magnetic/domain/user/dto/MyPageResponseDto.java
  src/main/java/com/magnetic/domain/user/entity/UserChallenge.java
  src/main/java/com/magnetic/domain/user/entity/UserCrew.java
  src/main/java/com/magnetic/domain/user/repository/UserChallengeRepository.java
  src/main/java/com/magnetic/domain/user/repository/UserCrewRepository.java
  src/main/java/com/magnetic/domain/user/repository/UserRepository.java
  src/main/java/com/magnetic/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/magnetic/domain/user/repository/impl/UserRepositoryCustomImpl.java
  src/main/java/com/magnetic/domain/user/service/MyPageService.java
  src/main/java/com/magnetic/domain/user/service/UserService.java
Labels: :sparkles: feature

#19 :sparkles: [FEATURE] 캘린더 조회, 추가, 수정, 삭제, 상태 변경 기능 추가
  src/main/java/com/magnetic/domain/calendar/controller/CalendarController.java
  src/main/java/com/magnetic/domain/calendar/converter/CalendarConverter.java
  src/main/java/com/magnetic/domain/calendar/dto/CalendarRequest.java
  src/main/java/com/magnetic/domain/calendar/dto/CalendarResponse.java
  src/main/java/com/magnetic/domain/calendar/entity/Todo.java
  src/main/java/com/magnetic/domain/calendar/repository/TodoRepository.java
  src/main/java/com/magnetic/domain/calendar/service/CalendarService.java
  src/main/java/com/magnetic/domain/challenge/entity/Challenge.java
  src/main/java/com/magnetic/domain/user/entity/User.java
  src/main/java/com/magnetic/global/common/code/status/ErrorStatus.java
  src/main/java/com/magnetic/global/common/exception/handler/CalendarHandler.java
Labels: :sparkles: feature

#21 ✨ [FEATURE] 관리자 마이크루 관련 기능 추가, 챌린지 화면 공유할 크루 목록 조회 기능 추가
  src/main/java/com/magnetic/config/SecurityConfig.java
  src/main/java/com/magnetic/domain/challenge/controller/ChallengeController.java
  src/main/java/com/magnetic/domain/challenge/converter/ChallengeConverter.java
  src/main/java/com/magnetic/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/magnetic/domain/challenge/service/ChallengeService.java
  src/main/java/com/magnetic/domain/crew/entity/Post.java
  src/main/java/com/magnetic/domain/crew/repository/CrewRepository.java
  src/main/java/com/magnetic/domain/user/controller/MyPageController.java
  src/main/java/com/magnetic/domain/user/converter/UserConverter.java
  src/main/java/com/magnetic/domain/user/dto/MyPageResponseDto.java
  src/main/java/com/magnetic/domain/user/entity/User.java
  src/main/java/com/magnetic/domain/user/entity/UserChallenge.java
  src/main/java/com/magnetic/domain/user/repository/UserChallengeRepository.java
  src/main/java/com/magnetic/domain/user/repository/UserCrewRepository.java
  src/main/java/com/magnetic/domain/user/service/MyPageService.java
  src/main/java/com/magnetic/global/common/code/status/ErrorStatus.java
  src/main/java/com/magnetic/global/common/exception/handler/ChallengeHandler.java
  src/main/java/com/magnetic/global/common/exception/handler/PostHandler.java
Labels: :sparkles: feature

#22 :sparkles: [FEATURE] 플랜트 관련 기능 추가 (#7)
  src/main/java/com/magnetic/domain/plant/controller/PlantController.java
  src/main/java/com/magnetic/domain/plant/dto/PlantRequest.java
  src/main/java/com/magnetic/domain/plant/dto/PlantResponse.java
  src/main/java/com/magnetic/domain/plant/entity/Plant.java
  src/main/java/com/magnetic/domain/plant/repository/PlantRepository.java
  src/main/java/com/magnetic/domain/plant/repository/PlantRepositoryCustom.java
  src/main/java/com/magnetic/domain/plant/repository/impl/PlantRepositoryCustomImpl.java
  src/main/java/com/magnetic/domain/plant/service/PlantService.java
  src/main/java/com/magnetic/domain/user/entity/User.java
  src/main/java/com/magnetic/domain/user/entity/UserPlant.java
  src/main/java/com/magnetic/domain/user/repository/UserPlantRepository.java
  src/main/java/com/magnetic/global/common/code/status/ErrorStatus.java
Labels: :sparkles: feature

#23 merge yejin
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/controller/LikeController.java
  src/main/java/com/magnetic/domain/crew/controller/PostController.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CreateCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CrewResponseDto.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/JoinCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/UpdateCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/likedto/LikeResponseDto.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/CreatePostRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/PostResponseDto.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/UpdatePostRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/crewdto/JoinCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/crewdto/LeaveCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/likedto/LikeRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/postdto/CreatePostRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/replydto/CreateReplyRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/request/replydto/UpdateReplyRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/response/PostResponseDto.java
  src/main/java/com/magnetic/domain/crew/entity/Crew.java
  src/main/java/com/magnetic/domain/crew/entity/Like.java
  src/main/java/com/magnetic/domain/crew/entity/Post.java
  src/main/java/com/magnetic/domain/crew/entity/Reply.java
  src/main/java/com/magnetic/domain/crew/repository/CrewRepository.java
  src/main/java/com/magnetic/domain/crew/repository/LikeRepository.java
  src/main/java/com/magnetic/domain/crew/repository/ReplyRepository.java
  src/main/java/com/magnetic/domain/crew/service/CrewService.java
  src/main/java/com/magnetic/domain/crew/service/LikeService.java
  src/main/java/com/magnetic/domain/crew/service/PostService.java
  src/main/java/com/magnetic/domain/user/entity/User.java
  src/main/java/com/magnetic/domain/user/repository/UserRepository.java
  src/main/java/com/magnetic/domain/user/service/UserService.java
Labels: :sparkles: feature

#24 update: Crew 도메인 postType -> category로 수정
  src/main/java/com/magnetic/domain/crew/dto/postdto/CreatePostRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/PostResponseDto.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/UpdatePostRequestDto.java
  src/main/java/com/magnetic/domain/crew/entity/Post.java
Labels: :lipstick: style

#25 Yejin
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/controller/LikeController.java
  src/main/java/com/magnetic/domain/crew/controller/PostController.java
  src/main/java/com/magnetic/domain/crew/controller/ReplyController.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CreateCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CrewResponseDto.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/JoinCrewDto.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/JoinCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/likedto/LikeResponseDto.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/CreatePostRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/replydto/ReplyRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/replydto/ReplyResponseDto.java
  src/main/java/com/magnetic/domain/crew/entity/Crew.java
  src/main/java/com/magnetic/domain/crew/entity/Like.java
  src/main/java/com/magnetic/domain/crew/entity/Reply.java
  src/main/java/com/magnetic/domain/crew/repository/LikeRepository.java
  src/main/java/com/magnetic/domain/crew/repository/PostRepository.java
  src/main/java/com/magnetic/domain/crew/repository/ReplyRepository.java
  src/main/java/com/magnetic/domain/crew/service/CrewService.java
  src/main/java/com/magnetic/domain/crew/service/LikeService.java
  src/main/java/com/magnetic/domain/crew/service/ReplyService.java
  src/main/java/com/magnetic/domain/user/entity/UserCrew.java
  src/main/java/com/magnetic/domain/user/repository/UserCrewRepository.java
  src/main/java/com/magnetic/domain/user/repository/UserRepository.java
Labels: :sparkles: feature

#26 ✨ [FEATURE] 프로필 사진 기능 추가
  gradlew
  gradlew.bat
  src/main/java/com/magnetic/config/S3Config.java
  src/main/java/com/magnetic/domain/plant/controller/PlantController.java
  src/main/java/com/magnetic/domain/plant/dto/PlantResponse.java
  src/main/java/com/magnetic/domain/plant/service/PlantService.java
  src/main/java/com/magnetic/domain/user/controller/MyPageController.java
  src/main/java/com/magnetic/domain/user/controller/UserController.java
  src/main/java/com/magnetic/domain/user/dto/UserRequestDto.java
  src/main/java/com/magnetic/domain/user/entity/User.java
  src/main/java/com/magnetic/domain/user/entity/UserChallenge.java
  src/main/java/com/magnetic/domain/user/repository/UserChallengeRepository.java
  src/main/java/com/magnetic/domain/user/service/MyPageService.java
  src/main/java/com/magnetic/domain/user/service/UserService.java
  src/main/java/com/magnetic/global/common/code/status/ErrorStatus.java
  src/main/java/com/magnetic/s3/S3Manager.java
Labels: :sparkles: feature

#28 :ambulance: hotfix: Cors 오류 해결
  src/main/java/com/magnetic/domain/auth/controller/AuthController.java
  src/main/java/com/magnetic/domain/calendar/controller/CalendarController.java
  src/main/java/com/magnetic/domain/challenge/controller/ChallengeController.java
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/controller/LikeController.java
  src/main/java/com/magnetic/domain/crew/controller/PostController.java
  src/main/java/com/magnetic/domain/crew/controller/ReplyController.java
  src/main/java/com/magnetic/domain/crew/controller/ReportController.java
  src/main/java/com/magnetic/domain/email/controller/EmailController.java
  src/main/java/com/magnetic/domain/plant/controller/PlantController.java
  src/main/java/com/magnetic/domain/user/controller/MyPageController.java
  src/main/java/com/magnetic/domain/user/controller/UserController.java
Labels: :ambulance: hotfix

#29 ✨ [FEATURE] 크루, 마이페이지 API 수정
  src/main/java/com/magnetic/domain/auth/controller/AuthController.java
  src/main/java/com/magnetic/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/controller/PostController.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CrewResponseDto.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/JoinCrewDto.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/PostResponseDto.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/QueryPostResponse.java
  src/main/java/com/magnetic/domain/crew/entity/Crew.java
  src/main/java/com/magnetic/domain/crew/repository/CrewPostRepository.java
  src/main/java/com/magnetic/domain/crew/repository/CrewRepository.java
  src/main/java/com/magnetic/domain/crew/repository/CrewRepositoryCustom.java
  src/main/java/com/magnetic/domain/crew/repository/LikeRepository.java
  src/main/java/com/magnetic/domain/crew/repository/PostRepository.java
  src/main/java/com/magnetic/domain/crew/repository/ReplyRepository.java
  src/main/java/com/magnetic/domain/crew/repository/ReportRepository.java
  src/main/java/com/magnetic/domain/crew/repository/impl/CrewRepositoryCustomImpl.java
  src/main/java/com/magnetic/domain/crew/service/CrewService.java
  src/main/java/com/magnetic/domain/crew/service/PostService.java
  src/main/java/com/magnetic/domain/user/controller/UserController.java
  src/main/java/com/magnetic/domain/user/dto/MyPageResponseDto.java
  src/main/java/com/magnetic/domain/user/entity/UserCrew.java
  src/main/java/com/magnetic/domain/user/repository/UserCrewRepository.java
  src/main/java/com/magnetic/domain/user/service/UserService.java
  src/main/java/com/magnetic/global/common/code/status/ErrorStatus.java
  src/main/java/com/magnetic/s3/S3Manager.java
Labels: :sparkles: feature

#30 :ambulance: hotfix: 크루 전체 조회 오류 수정, 이메일 검증 기능 추가 (#8)
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CrewResponseDto.java
  src/main/java/com/magnetic/domain/crew/repository/impl/CrewRepositoryCustomImpl.java
  src/main/java/com/magnetic/domain/user/controller/UserController.java
Labels: :ambulance: hotfix

#31 :ambulance: hotfix: 크루 전체 조회 오류 수정 (#8)
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CrewResponseDto.java
  src/main/java/com/magnetic/domain/crew/repository/impl/CrewRepositoryCustomImpl.java
Labels: :ambulance: hotfix

#32 ✨ feat: 게시글 신고하기 기능 추가 (#8)
  src/main/java/com/magnetic/domain/crew/controller/ReportController.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/JoinCrewDto.java
  src/main/java/com/magnetic/domain/crew/dto/reportdto/ReportDto.java
  src/main/java/com/magnetic/domain/crew/dto/reportdto/ReportRequestDto.java
  src/main/java/com/magnetic/domain/crew/entity/Report.java
  src/main/java/com/magnetic/domain/crew/service/ReportService.java
Labels: :sparkles: feature

#34 :sparkles: [FEATURE] 특정 크루 조회 기능 추가 (#8)
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/converter/CrewConverter.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CrewCustomResponse.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CrewResponseDto.java
  src/main/java/com/magnetic/domain/crew/repository/CrewChallengeRepository.java
  src/main/java/com/magnetic/domain/crew/service/CrewService.java
  src/main/java/com/magnetic/domain/user/repository/UserCrewRepository.java
Labels: :sparkles: feature

#35 🔧 [FIX] 기능 수정
  src/main/java/com/magnetic/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/magnetic/domain/challenge/repository/impl/ChallengeRepositoryImpl.java
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/controller/PostController.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/CreatePostRequestDto.java
  src/main/java/com/magnetic/domain/crew/service/PostService.java
  src/main/java/com/magnetic/domain/user/controller/UserController.java
Labels: :sparkles: feature

#36 :sparkles: [FEATURE] 특정 크루 커뮤니티 게시글 목록 조회 기능 추가
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/controller/PostController.java
  src/main/java/com/magnetic/domain/crew/converter/PostConverter.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/QueryPostResponse.java
  src/main/java/com/magnetic/domain/crew/entity/Crew.java
  src/main/java/com/magnetic/domain/crew/entity/Post.java
  src/main/java/com/magnetic/domain/crew/repository/CrewRepositoryCustom.java
  src/main/java/com/magnetic/domain/crew/repository/impl/CrewRepositoryCustomImpl.java
  src/main/java/com/magnetic/domain/crew/service/CrewService.java
  src/main/java/com/magnetic/domain/crew/service/PostService.java
Labels: :sparkles: feature

#37 :sparkles: [FEATURE] 기능 버그 및 편의성 수정
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CrewCustomResponse.java
  src/main/java/com/magnetic/domain/crew/service/CrewService.java
  src/main/java/com/magnetic/domain/user/dto/MyPageResponseDto.java
  src/main/java/com/magnetic/domain/user/service/MyPageService.java
Labels: :sparkles: feature

#38 :sparkles: [FEATURE] 이미지 업로드 관련 버그 수정
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/controller/PostController.java
Labels: :sparkles: feature

#39 ✨ [FEATURE] 신고 기능 수정, 좋아요 기능 추가
  src/main/java/com/magnetic/domain/crew/controller/PostController.java
  src/main/java/com/magnetic/domain/crew/controller/ReportController.java
  src/main/java/com/magnetic/domain/crew/dto/reportdto/ReportDto.java
  src/main/java/com/magnetic/domain/crew/dto/reportdto/ReportRequestDto.java
  src/main/java/com/magnetic/domain/crew/entity/Crew.java
  src/main/java/com/magnetic/domain/crew/entity/Post.java
  src/main/java/com/magnetic/domain/crew/entity/Report.java
  src/main/java/com/magnetic/domain/crew/repository/PostRepository.java
  src/main/java/com/magnetic/domain/crew/repository/ReportRepository.java
  src/main/java/com/magnetic/domain/crew/service/LikeService.java
  src/main/java/com/magnetic/domain/crew/service/PostService.java
  src/main/java/com/magnetic/domain/crew/service/ReportService.java
  src/main/java/com/magnetic/domain/user/entity/User.java
Labels: :sparkles: feature

#40 :sparkles: [FEATURE] 특정 챌린지 참여 크루 기능 추가, 플랜트 화면 유저 보유 토큰수 반환 속성 추가
  src/main/java/com/magnetic/domain/challenge/controller/ChallengeController.java
  src/main/java/com/magnetic/domain/challenge/converter/ChallengeConverter.java
  src/main/java/com/magnetic/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/magnetic/domain/challenge/service/ChallengeService.java
  src/main/java/com/magnetic/domain/crew/repository/CrewChallengeRepository.java
  src/main/java/com/magnetic/domain/plant/dto/PlantResponse.java
  src/main/java/com/magnetic/domain/plant/service/PlantService.java
Labels: :sparkles: feature

#41 :sparkles: feat: 게시글, 사진 따로 업로드 방식으로 수정 (#33)
  src/main/java/com/magnetic/MagneticApplication.java
  src/main/java/com/magnetic/config/SecurityConfig.java
  src/main/java/com/magnetic/domain/crew/controller/PostController.java
  src/main/java/com/magnetic/domain/crew/controller/ReplyController.java
  src/main/java/com/magnetic/domain/crew/converter/PostConverter.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/CreatePostRequestDto.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/PostResponseDto.java
  src/main/java/com/magnetic/domain/crew/dto/replydto/ReplyResponseDto.java
  src/main/java/com/magnetic/domain/crew/entity/Post.java
  src/main/java/com/magnetic/domain/crew/entity/Reply.java
  src/main/java/com/magnetic/domain/crew/service/PostService.java
  src/main/java/com/magnetic/domain/crew/service/ReplyService.java
Labels: :sparkles: feature

#42 🚑 hotfix: 마이 페이지 관련 버그 수정, CI/CD 스크립트 수정
  .github/workflows/main.yml
  src/main/java/com/magnetic/domain/user/dto/MyPageResponseDto.java
  src/main/java/com/magnetic/domain/user/repository/UserCrewRepository.java
  src/main/java/com/magnetic/domain/user/repository/impl/UserRepositoryCustomImpl.java
Labels: :ambulance: hotfix

#43 :bug: fix: 마이 페이지 조회 리스트 안의 리스트 해결
  src/main/java/com/magnetic/domain/user/dto/MyPageResponseDto.java
  src/main/java/com/magnetic/domain/user/service/MyPageService.java
Labels: :sparkles: feature

#44 :sparkles: [FEATURE] 크루 커뮤니티 게시글 등록 완료 반환값 추가
  src/main/java/com/magnetic/domain/crew/controller/PostController.java
  src/main/java/com/magnetic/domain/crew/dto/postdto/QueryPostResponse.java
  src/main/java/com/magnetic/domain/crew/service/PostService.java
Labels: :sparkles: feature

#45 :sparkles: [FEATURE] 크루 커뮤니티 게시글 상세 조회 기능 (댓글 목록 및 각 댓글 정보 포함) (#33)
  src/main/java/com/magnetic/domain/crew/converter/PostConverter.java
  src/main/java/com/magnetic/domain/crew/dto/replydto/ReplyResponseDto.java
  src/main/java/com/magnetic/domain/crew/service/PostService.java
Labels: :sparkles: feature

#46 :bug: [FIX] 식물 해금 오류 수정
  src/main/java/com/magnetic/config/SecurityConfig.java
  src/main/java/com/magnetic/domain/plant/service/PlantService.java
  src/main/java/com/magnetic/domain/user/entity/UserPlant.java
  src/main/java/com/magnetic/domain/user/service/UserService.java
Labels: :sparkles: feature

#47 ✨ [FEATURE] 식물 목록 조회 반환 데이터 형식 수정
  src/main/java/com/magnetic/domain/plant/controller/PlantController.java
  src/main/java/com/magnetic/domain/plant/dto/PlantResponse.java
  src/main/java/com/magnetic/domain/plant/repository/PlantRepository.java
  src/main/java/com/magnetic/domain/plant/repository/impl/PlantRepositoryCustomImpl.java
Labels: :sparkles: feature

#49 ✨ [FEATURE] 크루 플랜트 조회 기능 추가
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CrewPlantResponseDto.java
  src/main/java/com/magnetic/domain/crew/repository/CrewRepository.java
  src/main/java/com/magnetic/domain/crew/repository/CrewRepositoryCustom.java
  src/main/java/com/magnetic/domain/crew/repository/impl/CrewRepositoryCustomImpl.java
  src/main/java/com/magnetic/domain/crew/service/CrewService.java
  src/main/java/com/magnetic/domain/user/repository/UserRepository.java
Labels: :sparkles: feature

#50 :bug: fix: 크루 플랜트 조회 기능 버그 수정 (#33)
  src/main/java/com/magnetic/domain/crew/repository/CrewRepositoryCustom.java
  src/main/java/com/magnetic/domain/crew/repository/impl/CrewRepositoryCustomImpl.java
  src/main/java/com/magnetic/domain/crew/service/CrewService.java
  src/main/java/com/magnetic/domain/user/repository/UserCrewRepository.java
  src/main/java/com/magnetic/domain/user/repository/UserPlantRepository.java
Labels: :ambulance: hotfix

#51 [FIX] 크루 커뮤니티 게시글 생성, 삭제시 crew post 매핑 테이블 데이터 변동 추가 (#48)
  src/main/java/com/magnetic/domain/crew/controller/PostController.java
  src/main/java/com/magnetic/domain/crew/repository/CrewPostRepository.java
  src/main/java/com/magnetic/domain/crew/service/PostService.java
Labels: :sparkles: feature

#52 :sparkles: feat: Crew 생성 Api 분리
  src/main/java/com/magnetic/domain/crew/controller/CrewController.java
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CreateCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/service/CrewService.java
Labels: :sparkles: feature

#53 :bug: [FIX] 기능 수정
  src/main/java/com/magnetic/domain/auth/service/AuthService.java
  src/main/java/com/magnetic/domain/calendar/entity/Todo.java
  src/main/java/com/magnetic/domain/crew/entity/Crew.java
  src/main/java/com/magnetic/domain/crew/entity/Like.java
  src/main/java/com/magnetic/domain/crew/entity/Post.java
  src/main/java/com/magnetic/domain/plant/controller/PlantController.java
  src/main/java/com/magnetic/domain/plant/service/PlantService.java
  src/main/java/com/magnetic/domain/user/entity/User.java
  src/main/java/com/magnetic/domain/user/entity/UserChallenge.java
  src/main/java/com/magnetic/domain/user/entity/UserPlant.java
  src/main/java/com/magnetic/domain/user/repository/UserCrewRepository.java
  src/main/java/com/magnetic/domain/user/repository/UserPlantRepository.java
Labels: :ambulance: hotfix

#54 :bug: fix: 식물 해금, 목록 조회 오류 수정 (#48)
  src/main/java/com/magnetic/domain/plant/controller/PlantController.java
  src/main/java/com/magnetic/domain/plant/dto/PlantResponse.java
  src/main/java/com/magnetic/domain/plant/repository/impl/PlantRepositoryCustomImpl.java
  src/main/java/com/magnetic/domain/plant/service/PlantService.java
Labels: :ambulance: hotfix

#55 :bug: fix: 게시글 생성 오류 수정 (#48)
  src/main/java/com/magnetic/domain/crew/service/PostService.java
Labels: :ambulance: hotfix

#56 :bug: [FIX] 메인 식물 변경 오류 수정 (#48)
  src/main/java/com/magnetic/domain/plant/service/PlantService.java
  src/main/java/com/magnetic/domain/user/entity/UserPlant.java
  src/main/java/com/magnetic/domain/user/repository/UserPlantRepository.java
Labels: :ambulance: hotfix

#57 :bug: fix: 메인 식물 변경 오류 수정 (#48)
  src/main/java/com/magnetic/domain/plant/controller/PlantController.java
  src/main/java/com/magnetic/domain/plant/service/PlantService.java
Labels: :ambulance: hotfix

#58 :bug: [FIX] 게시글 생성 오류 수정 (#48)
  src/main/java/com/magnetic/domain/crew/dto/crewdto/CreateCrewRequestDto.java
  src/main/java/com/magnetic/domain/crew/entity/Crew.java
  src/main/java/com/magnetic/domain/crew/entity/Like.java
  src/main/java/com/magnetic/domain/crew/entity/Post.java
  src/main/java/com/magnetic/domain/user/entity/UserChallenge.java
  src/main/java/com/magnetic/domain/user/entity/UserCrew.java
  src/main/java/com/magnetic/domain/user/entity/UserPlant.java
Labels: :ambulance: hotfix

#60 :bug: fix: 오류 수정 (#48)
  src/main/java/com/magnetic/domain/user/controller/MyPageController.java
Labels: :ambulance: hotfix

#61 :bug: [FIX] 마이 크루 커뮤니티 확인시 인증 카테고리 게시글만 조회
  src/main/java/com/magnetic/domain/crew/repository/CrewPostRepository.java
Labels: :ambulance: hotfix

#62 :bug: [FIX] 인증글 검증 쿼리 수정
  src/main/java/com/magnetic/domain/crew/entity/Post.java
  src/main/java/com/magnetic/domain/crew/repository/CrewPostRepository.java
Labels: :ambulance: hotfix

#63 :bug: fix: 회원가입시 지급되는 식물 기능 수정 (#48)
  src/main/java/com/magnetic/domain/auth/service/AuthService.java
Labels: :ambulance: hotfix
